### ISSUE TITLE
Using un-supported characters in variable names makes the script unusable in a browser

### ISSUE THREAD

**Issue by kodie** [commenthol/astronomia#2]
Variable names such as [this](https://github.com/commenthol/astronomia/blob/a06b41e10ed940adb4b57d41f596856a3b9651eb/src/base.js#L214) cause a "Uncaught SyntaxError: Invalid or unexpected token" error in browser windows.

If these variable names were changed to use only characters from the english alphabet, this package along with all packages that depend on it (such as your [date-holidays](https://github.com/commenthol/date-holidays) package) could be compiled through [browserify](http://browserify.org) and used in web browsers.

**Comment by commenthol** [comment]
Hi @kodie, this package runs fine in modern browsers as is Chrome>=50 Firefox>=50 Edge>=15 Safari>=10. Would you mind sharing the exact browser version where you encounter this problem?

**Comment by kodie** [comment]
@commenthol I'm not sure what bundler package you are using to get this package to work in a browser but with browserify it definitely does not work.

![screen shot 2017-08-29 at 4 12 57 pm](https://user-images.githubusercontent.com/603949/29844651-a001d682-8cd5-11e7-99ed-8489eed885b0.png)

This is with Google Chrome Version 60.0.3112.101 (Official Build) (64-bit)

I created a test package where you can see exactly where it's failing: https://github.com/kodie/date-holidays-bundle-test

I have also submitted a pull request with this issue fixed: #3

**Comment by commenthol** [comment]
Please make sure to either use meta charset=UTF-8 in your page
```html
<html>
...
  <meta charset="UTF-8">
  ...
```
or include your bundle (e.g. bundle.js) with 
```html
<html>
  ...
<body>
  ...
  <script src="bundle.js" charset="UTF-8"></script>
  ...
```
Then all variables get resolved correctly.

**Comment by kodie** [comment]
Wow! I did not realize it was that simple, haha. I stand corrected!

Still though, is there a reason why you would prefer to specifically instruct users to add the charset parameter when including the script rather than just convert all of the greek characters?

This gets things rolling but for example I'll have to add to the installation instructions:

> Be sure to add charset="UTF-8" when embedding the script on your page due to the astronomia dependency needing it.

Not that that's a huge deal, but still a minor inconvenience.

Awesome package by the way.

**Comment by commenthol** [comment]
The package is a "translation" from go-lang and I like to keep things as close as possible. With the current set I still can easily incorporate fixes found in its parent. The greekish vars would make things more "unreadable" in such a case.

**Comment by kodie** [comment]
Understandable! Thank you!
