### ISSUE TITLE
optionalDependencies -> devDependencies

### ISSUE THREAD

**Issue by hayatae** [commenthol/astronomia#5]
Hello!

Could you please update the package.json file for this module to move your "optionalDependencies" into "devDependencies"? Right now if I install this module as a dependency of my project, it adds 255 packages (from the packages and all the dependents listed in optionalDependencies - mostly eslint). None of those packages are actually needed by or used by Astronomia when the code is used. Optional dependencies in package.json is normally used for packages that are OS dependent (such as fsevents).

Thanks!

**Comment by commenthol** [comment]
v1.3.8 contains fix.

**Comment by hayatae** [comment]
Thank you! 👍
